syntax = "proto3";
import "nanopb.proto";

message Acknowledge {
    bool success = 1;
}

message HilOut{
    float ax = 1;
    float ay = 2;
    float az = 3;

    float gx = 4;
    float gy = 5;
    float gz = 6;

    float p = 7;

    float lon = 8;
    float lat = 9;
    float alt = 10;

    uint32 time = 11;
}

message HilIn{
    float airbrake_percentage = 1;
    bool main_deployed = 2;
    bool drogue_deployed = 3;
}

message FjalarData {
    oneof data {
        HilIn hil_in = 15;
        HilOut hil_out = 16;
    };
}

message FjalarMessage {
    fixed32 time = 1;
    int32 sequence_number = 2;
    FjalarData data = 3;
}