# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: schemamatrocket.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'schemamatrocket.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15schemamatrocket.proto\x1a\x0cnanopb.proto\"\x1e\n\x0b\x41\x63knowledge\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\x90\x01\n\x06HilOut\x12\n\n\x02\x61x\x18\x01 \x01(\x02\x12\n\n\x02\x61y\x18\x02 \x01(\x02\x12\n\n\x02\x61z\x18\x03 \x01(\x02\x12\n\n\x02gx\x18\x04 \x01(\x02\x12\n\n\x02gy\x18\x05 \x01(\x02\x12\n\n\x02gz\x18\x06 \x01(\x02\x12\t\n\x01p\x18\x07 \x01(\x02\x12\x0b\n\x03lon\x18\x08 \x01(\x02\x12\x0b\n\x03lat\x18\t \x01(\x02\x12\x0b\n\x03\x61lt\x18\n \x01(\x02\x12\x0c\n\x04time\x18\x0b \x01(\r\"T\n\x05HilIn\x12\x1b\n\x13\x61irbrake_percentage\x18\x01 \x01(\x02\x12\x15\n\rmain_deployed\x18\x02 \x01(\x08\x12\x17\n\x0f\x64rogue_deployed\x18\x03 \x01(\x08\"J\n\nFjalarData\x12\x18\n\x06hil_in\x18\x0f \x01(\x0b\x32\x06.HilInH\x00\x12\x1a\n\x07hil_out\x18\x10 \x01(\x0b\x32\x07.HilOutH\x00\x42\x06\n\x04\x64\x61ta\"Q\n\rFjalarMessage\x12\x0c\n\x04time\x18\x01 \x01(\x07\x12\x17\n\x0fsequence_number\x18\x02 \x01(\x05\x12\x19\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x0b.FjalarDatab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemamatrocket_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACKNOWLEDGE']._serialized_start=39
  _globals['_ACKNOWLEDGE']._serialized_end=69
  _globals['_HILOUT']._serialized_start=72
  _globals['_HILOUT']._serialized_end=216
  _globals['_HILIN']._serialized_start=218
  _globals['_HILIN']._serialized_end=302
  _globals['_FJALARDATA']._serialized_start=304
  _globals['_FJALARDATA']._serialized_end=378
  _globals['_FJALARMESSAGE']._serialized_start=380
  _globals['_FJALARMESSAGE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
